[package]
name = "io_uring_test"
version = "0.1.0"
edition = "2021"
authors = ["sid6224"]
description = "Test processes for io_uring detection"

[dependencies]
io-uring = "0.6"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true 